-- Vider la table
DELETE FROM eval2_localisation;

-- Insérer les nouvelles données
INSERT INTO eval2_localisation (pays, poids) VALUES
('Afghanistan', 2),
('Albanie', 2),
('Algérie', 2),
('Angola', 2),
('Argentine', 2),
('Arménie', 1),
('Australie', 0),
('Autriche', 0),
('Azerbaïdjan', 2),
('Bahamas', 3),
('Bahreïn', 1),
('Bangladesh', 2),
('Barbade', 3),
('Bélarus', 2),
('Belgique', 0),
('Bénin', 1),
('Bhoutan', 0),
('Bolivie', 2),
('Bosnie-Herzégovine', 2),
('Botswana', 1),
('Brésil', 2),
('Bulgarie', 1),
('Burkina Faso', 1),
('Burundi', 2),
('Cabo Verde', 0),
('Cambodge', 2),
('Cameroun', 2),
('Canada', 0),
('République Centrafricaine', 2),
('Tchad', 2),
('Chili', 0),
('Chine', 1),
('Colombie', 1),
('Comores', 2),
('Congo', 2),
('Costa Rica', 1),
('Côte d''Ivoire', 1),
('Croatie', 1),
('Cuba', 1),
('Chypre', 3),
('Tchécoslovaquie', 1),
('République démocratique du Congo', 2),
('Danemark', 0),
('Djibouti', 2),
('Dominique', 1),
('République Dominicaine', 2),
('Équateur', 2),
('Égypte', 2),
('El Salvador', 2),
('Guinée équatoriale', 3),
('Erythrée', 2),
('Estonie', 0),
('Eswatini', 2),
('Éthiopie', 2),
('Fidji', 1),
('Finlande', 0),
('France', 0),
('Gabon', 2),
('Gambie', 2),
('Géorgie', 1),
('Allemagne', 0),
('Ghana', 1),
('Grèce', 1),
('Grenade', 3),
('Guatemala', 2),
('Guinée', 2),
('Guinée Bissau', 2),
('Guyana', 1),
('Haïti', 3),
('Honduras', 2),
('Hong Kong', 0),
('Hongrie', 1),
('Islande', 0),
('Inde', 2),
('Indonésie', 2),
('Iran', 2),
('Irak', 2),
('Irlande', 0),
('Israël', 0),
('Italie', 1),
('Jamaïque', 1),
('Japon', 0),
('Jordanie', 1),
('Kazakhstan', 2),
('Kenya', 2),
('Corée, Nord', 3),
('Corée, Sud', 0),
('Kosovo', 1),
('Koweït', 1),
('Kirghizistan', 2),
('Laos', 2),
('Lettonie', 0),
('Liban', 2),
('Lesotho', 2),
('Liberia', 2),
('Libye', 3),
('Lituanie', 0),
('Luxembourg', 0),
('Madagascar', 2),
('Malawi', 2),
('Malaisie', 1),
('Maldives', 2),
('Mali', 2),
('Malte', 1),
('Mauritanie', 2),
('Maurice', 3),
('Mexique', 2),
('Moldavie', 1),
('Mongolie', 2),
('Monténégro', 1),
('Maroc', 2),
('Mozambique', 2),
('Myanmar', 2),
('Namibie', 1),
('Népal', 2),
('Pays-Bas', 0),
('Nouvelle-Zélande', 0),
('Nicaragua', 3),
('Niger', 2),
('Nigeria', 2),
('Macédoine du Nord', 1),
('Norvège', 1),
('Oman', 1),
('Pakistan', 2),
('Panama', 2),
('Papouasie-Nouvelle-Guinée', 2),
('Paraguay', 2),
('Pérou', 2),
('Philippines', 2),
('Pologne', 1),
('Portugal', 0),
('Qatar', 1),
('Roumanie', 1),
('Russie', 3),
('Rwanda', 1),
('Sainte-Lucie', 1),
('Saint Vincent et les Grenadines', 0),
('Sao Tomé et Principe', 1),
('Arabie Saoudite', 1),
('Sénégal', 1),
('Serbie', 2),
('Seychelles', 0),
('Sierra Leone', 2),
('Singapour', 0),
('Slovaquie', 1),
('Slovénie', 1),
('Salomon (Îles)', 1),
('Somalie', 3),
('Afrique du Sud', 1),
('Sud-Soudan', 3),
('Espagne', 0),
('Sri Lanka', 2),
('Soudan', 2),
('Suriname', 1),
('Suède', 0),
('Suisse', 0),
('Syrie', 3),
('Taïwan', 0),
('Tadjikistan', 2),
('Tanzanie', 1),
('Thaïlande', 2),
('Timor-Leste', 1),
('Togo', 2),
('Trinité-et-Tobago', 1),
('Tunisie', 1),
('Turquie', 2),
('Turkménistan', 3),
('Ouganda', 2),
('Ukraine', 2),
('Emirats Arabes Unis', 0),
('Royaume-Uni', 0),
('Etats-Unis d''Amérique', 0),
('Uruguay', 0),
('Ouzbékistan', 2),
('Vanuatu', 1),
('Venezuela', 3),
('Vietnam', 1),
('Yémen', 3),
('Zambie', 2),
('Zimbabwe', 2);
